//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebNhaHangOnline.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KhoSP
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KhoSP()
        {
            this.TongSPKhoes = new HashSet<TongSPKho>();
        }
    
        public string IDKho { get; set; }
        public string MaSP { get; set; }
        public Nullable<int> SL { get; set; }
        public Nullable<System.DateTime> DateImport { get; set; }
        public Nullable<System.DateTime> DateExport { get; set; }
        public string TenSP { get; set; }
    
        public virtual SanPham SanPham { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TongSPKho> TongSPKhoes { get; set; }
    }
}
