//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebNhaHangOnline.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sanphamcanmua
    {
        public int ID { get; set; }
        public string MaSP { get; set; }
        public Nullable<int> Soluong { get; set; }
        public Nullable<System.DateTime> Ngayketthuc { get; set; }
        public Nullable<System.DateTime> Ngaydang { get; set; }
        public string Mota { get; set; }
        public string SanPham_Id { get; set; }
        public string NhaCungCap_Id { get; set; }
    
        public virtual NhaCungCap NhaCungCap { get; set; }
        public virtual SanPham SanPham { get; set; }
    }
}
