//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebNhaHangOnline.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TongSPKho
    {
        public string IDKho { get; set; }
        public string IDSP { get; set; }
        public Nullable<int> SL { get; set; }
    
        public virtual KhoSP KhoSP { get; set; }
    }
}
