//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestModel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DatBan
    {
        public int BookingId { get; set; }
        public string TableName { get; set; }
        public string UserId { get; set; }
        public string UserName { get; set; }
        public Nullable<int> TotalPerson { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string MaBan { get; set; }
        public string AspNetUserId { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Ban Ban { get; set; }
    }
}
