//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestModel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kho
    {
        public string KhoId { get; set; }
        public string Giatri { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public string ThuocTInh { get; set; }
    }
}
